const COOKIE_NAME="__Host-hotmix_session",ENCODER=new TextEncoder();
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store"}})}
function cookies(request){const result={};for(const part of String(request.headers.get("cookie")||"").split(";")){const i=part.indexOf("=");if(i>0)result[part.slice(0,i).trim()]=decodeURIComponent(part.slice(i+1).trim())}return result}
function b64(bytes){let s="";for(const byte of bytes)s+=String.fromCharCode(byte);return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")}
async function hash(value){return b64(new Uint8Array(await crypto.subtle.digest("SHA-256",ENCODER.encode(String(value||"")))))}
function equal(a,b){return a.byteLength===b.byteLength&&crypto.subtle.timingSafeEqual(a,b)}
async function session(request,env){const token=cookies(request)[COOKIE_NAME];if(!token)return null;const row=await env.DB.prepare(`SELECT s.csrf_token,s.user_id,u.role_key,u.active FROM auth_sessions s JOIN app_users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>? AND u.active=1 LIMIT 1`).bind(await hash(token),Date.now()).first();return row?{csrf:row.csrf_token,userId:row.user_id,roleKey:row.role_key}:null}
function csrf(request,current){const a=ENCODER.encode(String(request.headers.get("X-CSRF-Token")||"")),b=ENCODER.encode(String(current?.csrf||""));return a.byteLength>0&&equal(a,b)}
export default{async fetch(request,env){const current=await session(request,env);if(!current)return json({ok:false,error:"Sesi login diperlukan."},401);if(current.roleKey!=="admin")return json({ok:false,error:"Akses Admin diperlukan."},403);if(!csrf(request,current))return json({ok:false,error:"Validasi sesi gagal."},403);const body=await request.json().catch(()=>null);if(!body)return json({ok:false,error:"Payload tidak valid."},400);const id=String(body.id||""),name=String(body.displayName||"").trim().replace(/\s+/g," "),roleKey=String(body.roleKey||"").toLowerCase(),active=body.active===false?0:1;if(!id||name.length<2||name.length>120||!["admin","panitia01","viewer"].includes(roleKey))return json({ok:false,error:"Data user tidak valid."},400);if(id===current.userId&&(roleKey!=="admin"||!active))return json({ok:false,error:"Admin aktif tidak dapat menurunkan role atau menonaktifkan dirinya sendiri."},400);const legacyRole=roleKey==="viewer"?"Viewer":"Admin";const result=await env.DB.prepare("UPDATE app_users SET display_name=?,role=?,role_key=?,active=?,failed_attempts=0,locked_until=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(name,legacyRole,roleKey,active,id).run();if(!result.meta?.changes)return json({ok:false,error:"User tidak ditemukan."},404);if(id!==current.userId)await env.DB.prepare("DELETE FROM auth_sessions WHERE user_id=?").bind(id).run();return json({ok:true})}}
